# Generated by Django 3.1.7 on 2021-03-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='leader',
            new_name='user',
        ),
    ]
