# Generated by Django 3.1.7 on 2021-04-16 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210409_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='referees',
            field=models.ManyToManyField(related_name='referees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
