# Generated by Django 3.1.7 on 2021-04-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210409_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank='True', to='api.Team'),
        ),
    ]
