name: build frontend

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: clean build directory
        run: rm -rf dist/*
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
